# -*- coding: utf-8 -*-
"""477-lab-01 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12RwHL_x0rmFMGvr9M-Ctg3KM7_MpMuX6
"""

!pip install -q yt-dlp

import os
import matplotlib.pyplot as plt
from collections import Counter

import yt_dlp
def download_captions(video_url, lang='en', output_dir='/kaggle/working'):

    ydl_opts = {
        'skip_download': True,
        'writesubtitles': True,
        'writeautomaticsub': True,
        'subtitleslangs': [lang],
        'outtmpl': os.path.join(output_dir, '%(id)s.%(ext)s')
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(video_url, download=True)
        video_id = info['id']
        caption_file = os.path.join(output_dir, f"{video_id}.{lang}.vtt")
        if os.path.exists(caption_file):
            print(f"Captions downloaded: {caption_file}")
            return caption_file
        else:
            print("Captions not found!")
            return None

# Replace with your YouTube video URL
video_url = "https://youtu.be/h3M00JI8Iwo?si=aMdEGCrJrgIbZiIC"

caption_file = download_captions(video_url)

# Rename to captions.vtt for consistency
if caption_file:
    os.rename(caption_file, "/kaggle/working/captions.vtt")
    print("Renamed caption file to captions.vtt")

def load_vtt_captions(filepath="captions.vtt"):
    captions = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if (
                not line
                or "WEBVTT" in line
                or "-->" in line
                or line.isdigit()
                or "Kind:" in line
                or "Language:" in line
            ):
                continue
            # Remove inline timestamps like <00:00:05.920>
            while "<" in line and ">" in line:
                start = line.find("<")
                end = line.find(">", start)
                if end != -1:
                    line = line[:start] + line[end + 1:]
                else:
                    break
            line = line.strip()
            if line:
                captions.append(line)
    return captions

raw_captions = load_vtt_captions("/kaggle/working/captions.vtt")
print(f"Loaded {len(raw_captions)} caption lines")
print("Sample captions:", raw_captions[:5])

def load_raw_comments(filepath):
    comments = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if len(line) > 2:
                comments.append(line)
    return comments

# Replace 'YOUR_DATASET' with your Kaggle dataset folder name
raw_comments = load_raw_comments("/kaggle/input/commments/Comments.txt")
print(f"Loaded {len(raw_comments)} comment lines")
print("Sample comments:", raw_comments[:5])

caption_lengths = [len(x) for x in raw_captions]
comment_lengths = [len(x) for x in raw_comments]

plt.figure(figsize=(15,10))
plt.hist(caption_lengths, bins=20, alpha=0.7, label="Captions")
plt.hist(comment_lengths, bins=20, alpha=0.7, label="Comments")
plt.legend()
plt.xlabel("Length")
plt.ylabel("Frequency")
plt.show()

def type_token_ratio(lines):
    words = [word.lower() for line in lines for word in line.split()]
    unique_words = set(words)
    return len(unique_words)/len(words) if words else 0

print("Caption TTR:", type_token_ratio(raw_captions))
print("Comment TTR:", type_token_ratio(raw_comments))

import matplotlib.pyplot as plt

# Function to calculate TTR
def type_token_ratio(lines):
    words = [word.lower() for line in lines for word in line.split()]
    unique_words = set(words)
    return len(unique_words)/len(words) if words else 0

# Calculate TTR
ttr_captions = type_token_ratio(raw_captions)
ttr_comments = type_token_ratio(raw_comments)

# Bar plot
plt.figure(figsize=(15,10))
plt.bar(['Captions', 'Comments'], [ttr_captions, ttr_comments])
plt.ylim(0, 1)  # TTR is always between 0 and 1
plt.ylabel("Type-Token Ratio (TTR)")
plt.title("Vocabulary Diversity: Captions vs Comments")

for i, v in enumerate([ttr_captions, ttr_comments]):
    plt.text(i, v + 0.02, f"{v:.2f}", ha='center', fontweight='bold')

plt.show()

from collections import Counter
stopwords = {
    "the","and","a","is","in","to","of","that","it",
    "on","for","with","as","this","was","but","are",
    "not","be","at","by","an","if","or","from","so","we"
}

def top_n_words(lines, n=20):
    words = [
        word.lower()
        for line in lines
        for word in line.split()
        if word.lower() not in stopwords
    ]
    return Counter(words).most_common(n)

# ---------- Print caption words ----------
print("Top 20 caption words:")
for word, count in top_n_words(raw_captions):
    print(word, ":", count)

# ---------- Print comment words ----------
print("\nTop 20 comment words:")
for word, count in top_n_words(raw_comments):
    print(word, ":", count)

import matplotlib.pyplot as plt
from collections import Counter

# Function to get top N words
def top_n_words(lines, n=20, stopwords=None):
    if stopwords is None:
        stopwords = set()
    words = [word.lower() for line in lines for word in line.split() if word.lower() not in stopwords]
    return Counter(words).most_common(n)

# Stopwords set
stopwords = {
    "the","and","a","is","in","to","of","that","it",
    "on","for","with","as","this","was","but","are",
    "not","be","at","by","an","if","or","from","so","we"
}

# Top 20 words
top_captions = top_n_words(raw_captions, n=20, stopwords=stopwords)
top_comments = top_n_words(raw_comments, n=20, stopwords=stopwords)

# Plot for Captions
words_c, counts_c = zip(*top_captions)
plt.figure(figsize=(15,10))
plt.bar(words_c, counts_c)
plt.xticks(rotation=45, ha='right')
plt.title("Top 20 Caption Words", fontsize=16)
plt.ylabel("Frequency", fontsize=14)
plt.show()

# Plot for Comments
words_cm, counts_cm = zip(*top_comments)
plt.figure(figsize=(15,10))
plt.bar(words_cm, counts_cm)
plt.xticks(rotation=45, ha='right')
plt.title("Top 20 Comment Words", fontsize=16)
plt.ylabel("Frequency", fontsize=14)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# ---------- Load captions (.vtt file) ----------
captions_path = "/kaggle/working/captions.vtt"

with open(captions_path, 'r', encoding='utf-8') as file:
    lines = file.readlines()

captions = []
for line in lines:
    line = line.strip()
    if line == "" or "-->" in line or line.isdigit() or line.startswith("WEBVTT"):
        continue
    captions.append(line)

# ---------- Create DataFrame ----------
df_captions = pd.DataFrame({"caption": captions})

# ---------- Add caption length ----------
df_captions['caption_len'] = df_captions['caption'].apply(len)

# ---------- Moving Average (window = 20) ----------
df_captions['caption_len_ma'] = (
    df_captions['caption_len']
    .rolling(window=20)
    .mean()
)

# ---------- Plot ----------
plt.figure(figsize=(15, 10))

plt.plot(
    df_captions['caption_len_ma']
)

plt.title("Smoothed Caption Length Trend (Moving Average)")
plt.xlabel("Caption Index")
plt.ylabel("Average Caption Length")

plt.show()

plt.figure(figsize=(15, 10))

plt.boxplot(
    [caption_lengths, comment_lengths],
    labels=['Captions', 'Comments']
)

plt.ylabel("Text Length")
plt.title("Caption vs Comment Length Comparison")

plt.show()