# -*- coding: utf-8 -*-
"""Lab 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z19bqiGR9F_KHql_0JktbXpK7rSpHwTS
"""

!pip install webvtt-py

"""Importing Required Libraries"""

import pandas as pd
import re
import webvtt
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer

"""Downloading NLTK Resources"""

import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

"""Reading and Previewing Comments Text File"""

with open('/kaggle/input/comments-and-caption/Comments.txt', 'r', encoding='utf-8') as f:
    for i in range(20):
        print(f.readline())

"""Reading and Previewing Caption VTT File"""

with open('/kaggle/input/comments-and-caption/Caption.vtt', 'r', encoding='utf-8') as f:
    for i in range(20):
        print(f.readline())

"""Defining Function to Structure Comments from Text File"""

def structure_comments_from_txt(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    comments_data = []
    time_regex = re.compile(r'.*(second|minute|hour|day|week|month|year)s?\s+ago.*', re.IGNORECASE)

    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if i+1 < len(lines) and time_regex.match(lines[i+1].strip()):
            username = line
            timestamp = lines[i+1].strip()
            comment_text = []

            i += 2
            while i < len(lines) and not (
                i+1 < len(lines) and time_regex.match(lines[i+1].strip())
            ):
                text = lines[i].strip()
                if text and text.lower() not in ['reply', '...more']:
                    comment_text.append(text)
                i += 1

            if comment_text:
                comments_data.append({
                    'username': username,
                    'timestamp_text': timestamp,
                    'comment_text': ' '.join(comment_text)
                })
        else:
            i += 1

    return pd.DataFrame(comments_data)

"""Comments Load"""

comments_df = structure_comments_from_txt('//kaggle/input/comments-and-caption/Comments.txt')
comments_df.head()

"""Defining Function to Structure Captions from VTT File"""

def structure_captions_from_vtt(filepath):
    captions = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if '-->' not in line and line and not line.isdigit() and 'WEBVTT' not in line:
                captions.append(line)

    full_text = ' '.join(captions)
    sentences = re.split(r'(?<=[.!?]) +', full_text)
    return pd.DataFrame(sentences, columns=['caption_sentence'])

"""Caption Load"""

captions_df = structure_captions_from_vtt('/kaggle/input/comments-and-caption/Caption.vtt')
captions_df.head()

"""Defining a Function to Remove VTT Formatting Tags"""

def remove_vtt_tags(text):
    # remove common VTT tags like <c>, </c>, <i>, </i>, <v Speaker>
    text = re.sub(r'<.*?>', '', text)
    return text

"""Normalize Text"""

def normalize_text(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)          # remove brackets like [laugh]
    text = remove_vtt_tags(text)                 # remove VTT tags
    text = re.sub(r'[^a-z\s]', '', text)         # keep only letters and spaces
    text = text.strip()
    return text

"""Tokenization"""

def tokenize_text(text):
    return word_tokenize(text)

"""Stopword Removal"""

stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words and len(word) > 2]

"""Lemmatization & Stemming"""

lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

def stem_tokens(tokens):
    return [stemmer.stem(word) for word in tokens]

"""Full Cleaning Pipeline Function"""

def clean_text_pipeline(text, use_lemmatization=True):
    normalized = normalize_text(text)
    tokens = tokenize_text(normalized)
    filtered = remove_stopwords(tokens)

    if use_lemmatization:
        return lemmatize_tokens(filtered)
    else:
        return stem_tokens(filtered)

"""Apply on Comments DataFrame"""

comments_df['cleaned_tokens'] = comments_df['comment_text'].apply(
    lambda x: clean_text_pipeline(x, use_lemmatization=True)
)

comments_df.head()

"""Apply on Captions DataFrame"""

captions_df['cleaned_tokens'] = captions_df['caption_sentence'].apply(
    lambda x: clean_text_pipeline(x)
)

captions_df[['caption_sentence', 'cleaned_tokens']].head()

"""Printing for verification:"""

# Check the first few rows of cleaned comments and captions
print("Comments cleaned tokens:")
print(comments_df.head())

print("\nCaptions cleaned tokens:")
print(captions_df.head())

"""Stemming vs Lemmatization"""

sample_sentence = "studies studying cries cry"
tokens = tokenize_text(sample_sentence)

print("Stemmed:", stem_tokens(tokens))
print("Lemmatized:", lemmatize_tokens(tokens))

"""Save cleaned DataFrames to CSV"""

import os

folder_path = '/kaggle/working/cleaned_data'

os.makedirs(folder_path, exist_ok=True)

print("Folder exists:", os.path.exists(folder_path))

comments_df.to_csv(f'{folder_path}/cleaned_comments.csv', index=False)
captions_df.to_csv(f'{folder_path}/cleaned_captions.csv', index=False)
print("Files in cleaned_data folder:", os.listdir(folder_path))