# -*- coding: utf-8 -*-
"""Lab 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIvC1mDtFRhCtxF0oMkAVRebRuzhNl4v

## Required Libraries Import
"""

import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
from itertools import combinations
import networkx as nx

"""## Load Cleaned CSV Files"""

comments_df = pd.read_csv("/kaggle/input/cleaned-caption-and-comment/cleaned_comments.csv")
captions_df = pd.read_csv("/kaggle/input/cleaned-caption-and-comment/cleaned_captions.csv")

"""## Check basic structure of the DataFrames"""

from IPython.display import display

print("Comments DataFrame shape:", comments_df.shape)
display(comments_df.head())

print("Captions DataFrame shape:", captions_df.shape)
display(captions_df.head())

"""## Verify cleaned_tokens column exists"""

print("Columns in comments_df:", comments_df.columns)
print("Columns in captions_df:", captions_df.columns)

"""## Convert cleaned_tokens from string to list"""

import ast
# cleaned_tokens were stored as strings in CSV, converting to lists
if isinstance(comments_df['cleaned_tokens'].iloc[0], str):
    comments_df['cleaned_tokens'] = comments_df['cleaned_tokens'].apply(ast.literal_eval)

if isinstance(captions_df['cleaned_tokens'].iloc[0], str):
    captions_df['cleaned_tokens'] = captions_df['cleaned_tokens'].apply(ast.literal_eval)

"""## Drop rows where cleaned_tokens is missing or empty"""

comments_df = comments_df[comments_df['cleaned_tokens'].apply(lambda x: isinstance(x, list) and len(x) > 0)]
captions_df = captions_df[captions_df['cleaned_tokens'].apply(lambda x: isinstance(x, list) and len(x) > 0)]

print("After cleaning:")
print("Comments rows:", len(comments_df))
print("Captions rows:", len(captions_df))

"""## Top 20 unigrams for Comments"""

comment_tokens = []

for tokens in comments_df['cleaned_tokens']:
    comment_tokens.extend(tokens)

comment_counter = Counter(comment_tokens)

print("Top 20 Unigrams from Comments:\n")
for word, count in comment_counter.most_common(20):
    print(f"{word} : {count}")

"""## Top 20 unigrams for Captions"""

caption_tokens = []

for tokens in captions_df['cleaned_tokens']:
    caption_tokens.extend(tokens)

caption_counter = Counter(caption_tokens)

print("\nTop 20 Unigrams from Captions:\n")
for word, count in caption_counter.most_common(20):
    print(f"{word} : {count}")

"""## Install mlxtend"""

!pip install mlxtend

"""## Treat each list in cleaned_tokens as a transaction"""

# Each cleaned_tokens list in the DataFrame is treated as one transaction (basket)
comment_transactions = comments_df['cleaned_tokens'].tolist()
caption_transactions = captions_df['cleaned_tokens'].tolist()

print("Sample comment transaction:", comment_transactions[0])
print("Sample caption transaction:", caption_transactions[0])
print("Total comment transactions:", len(comment_transactions))
print("Total caption transactions:", len(caption_transactions))

"""## Remove baskets with fewer than 3 tokens"""

comment_transactions = [t for t in comment_transactions if len(t) >= 3]
caption_transactions = [t for t in caption_transactions if len(t) >= 3]

print("Transactions after length filter:")
print("Comments:", len(comment_transactions))
print("Captions:", len(caption_transactions))

"""## Optionally remove duplicate tokens within each basket"""

# Remove duplicates within each transaction
comment_transactions = [list(set(t)) for t in comment_transactions]
caption_transactions = [list(set(t)) for t in caption_transactions]

"""## Assign unique transaction IDs"""

# Assign unique transaction IDs
comment_transaction_ids = list(range(1, len(comment_transactions)+1))
caption_transaction_ids = list(range(1, len(caption_transactions)+1))
df_comment_transactions = pd.DataFrame({
    'TransactionID': comment_transaction_ids,
    'Items': comment_transactions
})

df_caption_transactions = pd.DataFrame({
    'TransactionID': caption_transaction_ids,
    'Items': caption_transactions
})

df_comment_transactions.head()

"""## Store cleaned transactions as list of lists"""

# Store as list of lists for later use
cleaned_comment_transactions = df_comment_transactions['Items'].tolist()
cleaned_caption_transactions = df_caption_transactions['Items'].tolist()

print("Type check:", type(cleaned_comment_transactions), "Sample:", cleaned_comment_transactions[0])

"""## Plot histogram of basket lengths"""

import matplotlib.pyplot as plt

# Comment transaction lengths
comment_lengths = [len(t) for t in cleaned_comment_transactions]

plt.figure(figsize=(15,10))
plt.hist(comment_lengths, bins=range(1, max(comment_lengths)+2), edgecolor='black', alpha=0.7)
plt.title("Histogram of Comment Transaction Lengths")
plt.xlabel("Number of Tokens")
plt.ylabel("Frequency")
plt.savefig("/kaggle/working/plots/comment_lengths_hist.png")
plt.show()
plt.close()

# Caption transaction lengths
caption_lengths = [len(t) for t in cleaned_caption_transactions]

plt.figure(figsize=(15,10))
plt.hist(caption_lengths, bins=range(1, max(caption_lengths)+2), edgecolor='black', alpha=0.7)
plt.title("Histogram of Caption Transaction Lengths")
plt.xlabel("Number of Tokens")
plt.ylabel("Frequency")
plt.savefig("/kaggle/working/plots/caption_lengths_hist.png")
plt.show()
plt.close()



"""## Print statistics (average, min, max basket length)"""

print("Comment Transactions Stats:")
print("Average length:", np.mean(comment_lengths))
print("Minimum length:", np.min(comment_lengths))
print("Maximum length:", np.max(comment_lengths))

print("\nCaption Transactions Stats:")
print("Average length:", np.mean(caption_lengths))
print("Minimum length:", np.min(caption_lengths))
print("Maximum length:", np.max(caption_lengths))

"""## Count pairwise co-occurrences (Comments)"""

comment_pair_counter = Counter()

for basket in cleaned_comment_transactions:
    pairs = combinations(sorted(set(basket)), 2)
    comment_pair_counter.update(pairs)

print("Total unique comment word pairs:", len(comment_pair_counter))

"""## Pairwise co-occurrence counting for CAPTIONS"""

caption_pair_counter = Counter()

for basket in cleaned_caption_transactions:
    pairs = combinations(sorted(set(basket)), 2)
    caption_pair_counter.update(pairs)
print("Total unique caption word pairs:", len(caption_pair_counter))

"""## Keep pairs with count ≥ 3 for Comments"""

comment_filtered_pairs = {
    pair: count
    for pair, count in comment_pair_counter.items()
    if count >= 3
}
print("Comment pairs with count ≥ 3:", len(comment_filtered_pairs))

"""## Keep pairs with count ≥ 3 for Captions"""

caption_filtered_pairs = {
    pair: count
    for pair, count in caption_pair_counter.items()
    if count >= 3
}

print("Caption pairs with count ≥ 3:", len(caption_filtered_pairs))

"""## Top 20 co-occurring pairs plot for Comments"""

import matplotlib.pyplot as plt
from collections import Counter
top_20_comment_pairs = Counter(comment_filtered_pairs).most_common(20)
labels = [f"{a}, {b}" for (a, b), _ in top_20_comment_pairs]
counts = [c for _, c in top_20_comment_pairs]

plt.figure(figsize=(15,10))
plt.barh(labels, counts)
plt.xlabel("Co-occurrence Count")
plt.ylabel("Word Pairs")
plt.title("Top 20 Co-occurring Word Pairs (Comments)")
plt.gca().invert_yaxis()
plt.savefig("/kaggle/working/plots/top_20_comment_pairs.png")
plt.show()
plt.close()

"""## Top 20 co-occurring pairs plot for Captions"""

import matplotlib.pyplot as plt
from collections import Counter


top_20_caption_pairs = Counter(caption_filtered_pairs).most_common(20)
labels = [f"{a}, {b}" for (a, b), _ in top_20_caption_pairs]
counts = [c for _, c in top_20_caption_pairs]
plt.figure(figsize=(15,10))
plt.barh(labels, counts)
plt.xlabel("Co-occurrence Count")
plt.ylabel("Word Pairs")
plt.title("Top 20 Co-occurring Word Pairs (Captions)")
plt.gca().invert_yaxis()
plt.savefig("/kaggle/working/plots/top_20_caption_pairs.png")
plt.show()
plt.close()

"""## Unigram frequency for Comments & C aptions"""

comment_unigrams = Counter()
for basket in cleaned_comment_transactions:
    comment_unigrams.update(basket)

top_20_comment_words = comment_unigrams.most_common(20)
words, freqs = zip(*top_20_comment_words)
plt.figure(figsize=(15,10))
plt.barh(words, freqs)
plt.xlabel("Frequency")
plt.ylabel("Words")
plt.title("Top 20 Unigrams (Comments)")
plt.gca().invert_yaxis()
plt.savefig("/kaggle/working/plots/top_20_comment_unigrams.png")
plt.show()
plt.close()

# Top 20 Unigrams - Captions

caption_unigrams = Counter()
for basket in cleaned_caption_transactions:
    caption_unigrams.update(basket)
top_20_caption_words = caption_unigrams.most_common(20)
words, freqs = zip(*top_20_caption_words)
plt.figure(figsize=(15,10))
plt.barh(words, freqs)
plt.xlabel("Frequency")
plt.ylabel("Words")
plt.title("Top 20 Unigrams (Captions)")
plt.gca().invert_yaxis()
plt.savefig("/kaggle/working/plots/top_20_caption_unigrams.png")
plt.show()
plt.close()

"""## Network graph for Comments"""

G_comment = nx.Graph()
for (w1, w2), count in comment_filtered_pairs.items():
    G_comment.add_edge(w1, w2, weight=count)

plt.figure(figsize=(25,25))
pos = nx.spring_layout(G_comment, k=0.4)
nx.draw(G_comment, pos, with_labels=True, node_size=700, font_size=9)
plt.title("Co-occurrence Network (Comments)")
plt.savefig("/kaggle/working/plots/cooccurrence_network_comments.png")
plt.show()
plt.close()

"""## Network graph for Captions"""

# Co-occurrence network - Captions
G_caption = nx.Graph()
for (w1, w2), count in caption_filtered_pairs.items():
    G_caption.add_edge(w1, w2, weight=count)

plt.figure(figsize=(20,20))
pos = nx.spring_layout(G_caption, k=0.4)
nx.draw(G_caption, pos, with_labels=True, node_size=700, font_size=9)
plt.title("Co-occurrence Network (Captions)")
plt.savefig("/kaggle/working/plots/cooccurrence_network_captions.png")
plt.show()
plt.close()

"""## Stopword filtering (Comments)"""

stopwords = {"the","and","to","of","is","in","for","on","this","that","it"}
comment_pairs_no_stopwords = {
    pair: count
    for pair, count in comment_filtered_pairs.items()
    if pair[0] not in stopwords and pair[1] not in stopwords
}
print("Comment pairs after stopword removal:", len(comment_pairs_no_stopwords))

"""## Stopword filtering (Captions)"""

caption_pairs_no_stopwords = {
    pair: count
    for pair, count in caption_filtered_pairs.items()
    if pair[0] not in stopwords and pair[1] not in stopwords
}
print("Caption pairs after stopword removal:", len(caption_pairs_no_stopwords))

"""## Export CSV (Comments)"""

comment_cooccurrence_df = pd.DataFrame(
    [(a, b, c) for (a, b), c in comment_pairs_no_stopwords.items()],
    columns=["Word1", "Word2", "Cooccurrence_Count"]
)
comment_cooccurrence_df.to_csv("comment_cooccurrence.csv", index=False)
print("comment_cooccurrence.csv exported")

"""## Export CSV (Captons)"""

caption_cooccurrence_df = pd.DataFrame(
    [(a, b, c) for (a, b), c in caption_pairs_no_stopwords.items()],
    columns=["Word1", "Word2", "Cooccurrence_Count"]
)
caption_cooccurrence_df.to_csv("caption_cooccurrence.csv", index=False)
print("caption_cooccurrence.csv exported")

"""## One-hot encode transactions for Comments and Captions"""

# One-hot encode transactions
transactions_comments = comments_df['cleaned_tokens'].dropna().tolist()
transactions_captions = captions_df['cleaned_tokens'].dropna().tolist()

def to_onehot_df(transactions):
    from mlxtend.preprocessing import TransactionEncoder
    import pandas as pd
    transactions = [t for t in transactions if len(t) > 0]
    te = TransactionEncoder()
    arr = te.fit(transactions).transform(transactions)
    df_onehot = pd.DataFrame(arr, columns=te.columns_).astype(bool)
    return df_onehot
onehot_comments = to_onehot_df(transactions_comments)
onehot_captions = to_onehot_df(transactions_captions)
print("One-hot shapes:")
print("Comments:", onehot_comments.shape)
print("Captions:", onehot_captions.shape)

"""## Apriori Results for COMMENTS and CAPTIONS (min_support = 0.3, 0.2, 0.1)"""

import warnings
warnings.filterwarnings("ignore")
from mlxtend.frequent_patterns import apriori, association_rules

def run_apriori(onehot_df, min_support):
    itemsets = apriori(onehot_df, min_support=min_support, use_colnames=True)
    itemsets["length"] = itemsets["itemsets"].apply(len)
    return itemsets.sort_values(["support", "length"], ascending=[False, True])
ap_comments_03 = run_apriori(onehot_comments, 0.3)
ap_comments_02 = run_apriori(onehot_comments, 0.2)
ap_comments_01 = run_apriori(onehot_comments, 0.1)
print("Itemsets comments @0.3:", len(ap_comments_03))
print("Itemsets comments @0.2:", len(ap_comments_02))
print("Itemsets comments @0.1:", len(ap_comments_01))
ap_captions_03 = run_apriori(onehot_captions, 0.3)
ap_captions_02 = run_apriori(onehot_captions, 0.2)
ap_captions_01 = run_apriori(onehot_captions, 0.1)
print("Itemsets captions @0.3:", len(ap_captions_03))
print("Itemsets captions @0.2:", len(ap_captions_02))
print("Itemsets captions @0.1:", len(ap_captions_01))

"""## For experiment (comment)"""

freq_c_03 = apriori(comment_ohe_df, min_support=0.03, use_colnames=True)
freq_c_02 = apriori(comment_ohe_df, min_support=0.02, use_colnames=True)
freq_c_01 = apriori(comment_ohe_df, min_support=0.01, use_colnames=True)
for df in [freq_c_03, freq_c_02, freq_c_01]:
    df["length"] = df["itemsets"].apply(len)
print("Comment itemsets @0.03:", len(freq_c_03))
print("Comment itemsets @0.02:", len(freq_c_02))
print("Comment itemsets @0.01:", len(freq_c_01))

"""## For experment (Caption)"""

freq_p_03 = apriori(caption_ohe_df, min_support=0.03, use_colnames=True)
freq_p_02 = apriori(caption_ohe_df, min_support=0.02, use_colnames=True)
freq_p_01 = apriori(caption_ohe_df, min_support=0.01, use_colnames=True)
for df in [freq_p_03, freq_p_02, freq_p_01]:
    df["length"] = df["itemsets"].apply(len)
print("Caption itemsets @0.03:", len(freq_p_03))
print("Caption itemsets @0.02:", len(freq_p_02))
print("Caption itemsets @0.01:", len(freq_p_01))

"""## Filter itemsets by length (keep 2 and 3 item sets) for Comments and Captions"""

def filter_itemsets_len(itemsets_df, lengths=(2, 3)):
    return itemsets_df[itemsets_df["length"].isin(lengths)].copy()
ap_comments_01_23 = filter_itemsets_len(ap_comments_01, (2,3))
ap_captions_01_23 = filter_itemsets_len(ap_captions_01, (2,3))
print("Comments itemsets len2/3 @0.1:", len(ap_comments_01_23))
print("Captions itemsets len2/3 @0.1 :", len(ap_captions_01_23))

"""## Association rules for Comments & Captions"""

def build_rules(itemsets_df, min_conf=0.6, min_lift=1.2):
    rules = association_rules(itemsets_df, metric="confidence", min_threshold=min_conf)
    rules = rules[(rules["confidence"] >= min_conf) & (rules["lift"] >= min_lift)].copy()
    rules["antecedents_str"] = rules["antecedents"].apply(lambda s: ", ".join(sorted(list(s))))
    rules["consequents_str"] = rules["consequents"].apply(lambda s: ", ".join(sorted(list(s))))
    return rules.sort_values(["lift", "confidence"], ascending=False)
rules_comments = build_rules(ap_comments_01, min_conf=0.6, min_lift=1.2)
rules_captions = build_rules(ap_captions_01, min_conf=0.6, min_lift=1.2)
print("Rules kept (comments):", len(rules_comments))
print("Rules kept (captions):", len(rules_captions))
rules_comments[["antecedents_str","consequents_str","support","confidence","lift"]].head(10)

"""## Plot support vs confidence scatter plot."""

def plot_support_confidence(rules_df, title, filename):
    if rules_df.empty:
        print("No rules to plot:", title)
        return
    plt.figure(figsize=(7, 5))
    plt.scatter(rules_df["support"], rules_df["confidence"])
    plt.title(title)
    plt.xlabel("Support")
    plt.ylabel("Confidence")
    plt.grid(True, alpha=0.2)
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, filename), dpi=200)
    plt.show()
    plt.close()
plot_support_confidence(rules_comments, "Support vs Confidence — Comments rules", "scatter_support_conf_comments.png")
plot_support_confidence(rules_captions, "Support vs Confidence — Captions rules", "scatter_support_conf_captions.png")

"""## Save frequent itemsets and association rules"""

CSVS_DIR = "csv_outputs"
os.makedirs(CSVS_DIR, exist_ok=True)
ap_comments_01_23.to_csv(os.path.join(CSVS_DIR, "frequent_itemsets_comments.csv"), index=False)
rules_comments.to_csv(os.path.join(CSVS_DIR, "association_rules_comments.csv"), index=False)
ap_captions_01_23.to_csv(os.path.join(CSVS_DIR, "frequent_itemsets_captions.csv"), index=False)
rules_captions.to_csv(os.path.join(CSVS_DIR, "association_rules_captions.csv"), index=False)
print("Saved frequent_itemsets.csv and association_rules.csv")

"""## min_support = 0.15, 0.05 for Comments & Captions"""

from mlxtend.frequent_patterns import apriori

# COMMENTS
freq_c_015 = apriori(comment_ohe_df, min_support=0.15, use_colnames=True)
freq_c_005 = apriori(comment_ohe_df, min_support=0.05, use_colnames=True)
print("Comments itemsets @0.15:", len(freq_c_015))
print("Comments itemsets @0.05 :", len(freq_c_005))

# CAPTIONS
freq_p_015 = apriori(caption_ohe_df, min_support=0.15, use_colnames=True)
freq_p_005 = apriori(caption_ohe_df, min_support=0.05, use_colnames=True)
print("Caption itemsets @0.15:", len(freq_p_015))
print("Caption itemsets @0.05 :", len(freq_p_005))

"""## Swap out lemmatization for stemming."""

from mlxtend.preprocessing import TransactionEncoder

try:
    from nltk.stem import PorterStemmer
    ps = PorterStemmer()
    def stem_word(w):
        return ps.stem(w)
    print("Using NLTK PorterStemmer.")
except Exception:
    def stem_word(w):
        for suf in ["ing","ed","ly","es","s"]:
            if w.endswith(suf) and len(w) > len(suf) + 2:
                return w[:-len(suf)]
        return w
    print("NLTK not available; using simple fallback stemmer.")

#Stem transactions function
def stem_transactions(transactions):
    out = []
    for basket in transactions:
        out.append(
            sorted(
                set(
                    stem_word(w.lower())
                    for w in basket
                    if isinstance(w,str) and w.strip()
                )
            )
        )
    return out

comments_tx_stem = stem_transactions(cleaned_comment_transactions)
captions_tx_stem = stem_transactions(cleaned_caption_transactions)

def onehot_encode(transactions):
    te = TransactionEncoder()
    arr = te.fit(transactions).transform(transactions)
    return pd.DataFrame(arr, columns=te.columns_)
onehot_comments_stem = onehot_encode(comments_tx_stem)
onehot_captions_stem = onehot_encode(captions_tx_stem)

ap_comments_stem_01 = run_apriori(onehot_comments_stem, 0.1)
rules_comments_stem = build_rules(ap_comments_stem_01, 0.6, 1.2)
print("Stemmed comments rules kept:", len(rules_comments_stem))

"""## Remove tokens under 4 characters"""

def filter_short_tokens(transactions, min_chars=4):
    out = []
    for basket in transactions:

        b = [w for w in basket if isinstance(w, str) and len(w) >= min_chars]
        b = sorted(set(b))
        if len(b) >= 3:
            out.append(b)
    return out
comments_tx_len4 = filter_short_tokens(cleaned_comment_transactions, 4)
onehot_comments_len4 = onehot_encode(comments_tx_len4)
ap_comments_len4_01 = run_apriori(onehot_comments_len4, 0.1)
rules_comments_len4 = build_rules(ap_comments_len4_01, 0.6, 1.2)
print("Len>=4 comments rules kept:", len(rules_comments_len4))

"""## Full pipeline for Captions"""

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

from mlxtend.frequent_patterns import apriori, association_rules
import ast
captions_df = pd.read_csv("/kaggle/input/cleaned-caption-and-comment/cleaned_captions.csv")
if isinstance(captions_df['cleaned_tokens'].iloc[0], str):
    captions_df['cleaned_tokens'] = captions_df['cleaned_tokens'].apply(ast.literal_eval)
captions_tx = captions_df['cleaned_tokens'].tolist()

try:
    from nltk.stem import PorterStemmer
    ps = PorterStemmer()
    def stem_word(w):
        return ps.stem(w)
    print("Using NLTK PorterStemmer.")
except Exception:
    def stem_word(w):
        for suf in ["ing","ed","ly","es","s"]:
            if w.endswith(suf) and len(w) > len(suf)+2:
                return w[:-len(suf)]
        return w
    print("NLTK not available; using simple fallback stemmer.")
def stem_transactions(transactions):
    out = []
    for basket in transactions:
        out.append(
            sorted(
                set(
                    stem_word(w.lower())
                    for w in basket
                    if isinstance(w,str) and w.strip()
                )
            )
        )
    return out

captions_tx_stem = stem_transactions(captions_tx)
def onehot_encode(transactions):
    te = TransactionEncoder()
    arr = te.fit(transactions).transform(transactions)
    return pd.DataFrame(arr, columns=te.columns_)
onehot_captions_stem = onehot_encode(captions_tx_stem)
def run_apriori(onehot_df, min_support):
    itemsets = apriori(onehot_df, min_support=min_support, use_colnames=True)
    itemsets["length"] = itemsets["itemsets"].apply(len)
    return itemsets.sort_values(["support","length"], ascending=[False,True])
def build_rules(itemsets_df, min_conf=0.6, min_lift=1.2):
    rules = association_rules(itemsets_df, metric="confidence", min_threshold=min_conf)
    rules = rules[(rules["confidence"] >= min_conf) & (rules["lift"] >= min_lift)].copy()
    rules["antecedents_str"] = rules["antecedents"].apply(lambda s: ", ".join(sorted(list(s))))
    rules["consequents_str"] = rules["consequents"].apply(lambda s: ", ".join(sorted(list(s))))
    return rules.sort_values(["lift","confidence"], ascending=False)
ap_captions_stem_01 = run_apriori(onehot_captions_stem, 0.1)
rules_captions_stem = build_rules(ap_captions_stem_01, 0.6, 1.2)
print("Stemmed captions itemsets @0.1:", len(ap_captions_stem_01))
print("Stemmed captions rules kept:", len(rules_captions_stem))
rules_captions_stem[["antecedents_str","consequents_str","support","confidence","lift"]].head(10)

"""##  Merge comments + captions and rerun Apriori."""

import ast
import os
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules


COMMENTS_PATH = "/kaggle/input/cleaned-caption-and-comment/cleaned_comments.csv"
CAPTIONS_PATH = "/kaggle/input/cleaned-caption-and-comment/cleaned_captions.csv"
CSVS_DIR = "/kaggle/working/csv_outputs"
os.makedirs(CSVS_DIR, exist_ok=True)
comments_df = pd.read_csv(COMMENTS_PATH)
if isinstance(comments_df['cleaned_tokens'].iloc[0], str):
    comments_df['cleaned_tokens'] = comments_df['cleaned_tokens'].apply(ast.literal_eval)
comments_tx = comments_df['cleaned_tokens'].dropna().tolist()
captions_df = pd.read_csv(CAPTIONS_PATH)
if isinstance(captions_df['cleaned_tokens'].iloc[0], str):
    captions_df['cleaned_tokens'] = captions_df['cleaned_tokens'].apply(ast.literal_eval)
captions_tx = captions_df['cleaned_tokens'].dropna().tolist()

def onehot_encode(transactions):
    transactions = [t for t in transactions if len(t) > 0]
    te = TransactionEncoder()
    arr = te.fit(transactions).transform(transactions)
    return pd.DataFrame(arr, columns=te.columns_)
def run_apriori(onehot_df, min_support):
    if onehot_df.empty: return pd.DataFrame()
    itemsets = apriori(onehot_df, min_support=min_support, use_colnames=True)
    itemsets["length"] = itemsets["itemsets"].apply(len)
    return itemsets.sort_values(["support","length"], ascending=[False,True])

def build_rules(itemsets_df, min_conf=0.6, min_lift=1.2):
    if itemsets_df.empty: return pd.DataFrame()
    rules = association_rules(itemsets_df, metric="confidence", min_threshold=min_conf)
    if rules.empty: return pd.DataFrame()
    rules = rules[(rules["confidence"] >= min_conf) & (rules["lift"] >= min_lift)].copy()
    rules["antecedents_str"] = rules["antecedents"].apply(lambda s: ", ".join(sorted(list(s))))
    rules["consequents_str"] = rules["consequents"].apply(lambda s: ", ".join(sorted(list(s))))
    return rules.sort_values(["lift","confidence"], ascending=False)
def filter_itemsets_len(itemsets_df, lengths=(2,3)):
    return itemsets_df[itemsets_df["length"].isin(lengths)].copy()
merged_tx = comments_tx + captions_tx
onehot_merged = onehot_encode(merged_tx)
ap_merged_01 = run_apriori(onehot_merged, 0.1)
rules_merged = build_rules(ap_merged_01, 0.6, 1.2)
ap_merged_01_23 = filter_itemsets_len(ap_merged_01, (2,3))
ap_merged_01_23.to_csv(os.path.join(CSVS_DIR, "frequent_itemsets_merged.csv"), index=False)
rules_merged.to_csv(os.path.join(CSVS_DIR, "association_rules_merged.csv"), index=False)
print("Merged rules kept:", len(rules_merged))

"""## Compare rules from merged vs separate datasets."""

def rule_key(df):
    if df.empty:
        return set()
    return set((a, c) for a, c in zip(df["antecedents_str"], df["consequents_str"]))

sep_keys = rule_key(rules_comments) | rule_key(rules_captions)
merged_keys = rule_key(rules_merged)
only_in_merged = sorted(list(merged_keys - sep_keys))[:30]
missing_in_merged = sorted(list(sep_keys - merged_keys))[:30]
print("Examples only-in-merged:")
for a,c in only_in_merged:
    print("  ", a, "->", c)
print("\nExamples present in separate but missing in merged:")
for a,c in missing_in_merged:
    print("  ", a, "->", c)

"""## Reflect patterns vanished or appeared under new settings"""

import os


TEXT_DIR = "./text_outputs"
os.makedirs(TEXT_DIR, exist_ok=True)
reflection_variations = []
reflection_variations.append(f"min_support 0.15 itemsets (comments): {len(ap_comments_015)}")
reflection_variations.append(f"min_support 0.05  itemsets (comments): {len(ap_comments_005)}")
reflection_variations.append(f"stemmed rules kept (comments): {len(rules_comments_stem)}")
reflection_variations.append(f"len>=4 rules kept (comments): {len(rules_comments_len4)}")
reflection_variations.append(f"merged rules kept: {len(rules_merged)}")
reflection_variations.append(f"only-in-merged sample count shown: {len(only_in_merged)}")
reflection_variations.append(f"missing-in-merged sample count shown: {len(missing_in_merged)}")
print("\n".join("- " + s for s in reflection_variations))
with open(os.path.join(TEXT_DIR, "variation_notes.txt"), "w", encoding="utf-8") as f:
    f.write("Variation Notes (Task 38)\n")
    f.write("\n".join(reflection_variations))
print("Saved variation notes:", os.path.join(TEXT_DIR, "variation_notes.txt"))

"""## Plot bar chart of top 10 2-itemsets by support"""

def plot_top_itemsets(itemsets_df, length, topn, title, filename):
    df = itemsets_df[itemsets_df["length"] == length].copy()
    df = df.sort_values("support", ascending=False).head(topn)
    if df.empty:
        print("No itemsets:", title)
        return

    labels = df["itemsets"].apply(lambda s: ", ".join(sorted(list(s)))).tolist()
    values = df["support"].tolist()
    plt.figure(figsize=(10, 5))
    plt.barh(labels[::-1], values[::-1])
    plt.title(title)
    plt.xlabel("Support")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, filename), dpi=200)
    plt.show()
    plt.close()
plot_top_itemsets(ap_comments_01, 2, 10, "Top 10 2-itemsets by support — Comments", "top10_2itemsets_support_comments.png")
plot_top_itemsets(ap_captions_01, 2, 10, "Top 10 2-itemsets by support — Captions", "top10_2itemsets_support_captions.png")

"""## Plot top 10 3-itemsets by confidence"""

def plot_top_rules_total_items(rules_df, total_items, topn, title, filename):
    if rules_df.empty:
        print("No rules:", title)
        return

    df = rules_df.copy()
    df["total_items"] = df["antecedents"].apply(len) + df["consequents"].apply(len)
    df = df[df["total_items"] == total_items].copy()
    df = df.sort_values(["confidence","lift"], ascending=False).head(topn)
    if df.empty:
        print("No rules with total_items =", total_items, "for", title)
        return
    labels = (df["antecedents_str"] + " -> " + df["consequents_str"]).tolist()
    values = df["confidence"].tolist()
    plt.figure(figsize=(10, 6))
    plt.barh(labels[::-1], values[::-1])
    plt.title(title)
    plt.xlabel("Confidence")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, filename), dpi=200)
    plt.show()
    plt.close()
plot_top_rules_total_items(rules_comments, 3, 10, "Top 10 (3 total items) rules by confidence — Comments", "top10_rules_conf_total3_comments.png")
plot_top_rules_total_items(rules_captions, 3, 10, "Top 10 (3 total items) rules by confidence — Captions", "top10_rules_conf_total3_captions.png")

"""## word cloud from most frequent items"""

import os
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from collections import Counter

PLOTS_DIR = "./plots"
os.makedirs(PLOTS_DIR, exist_ok=True)
counter_comments_tx = Counter([w for basket in comments_tx for w in basket])
counter_captions_tx = Counter([w for basket in captions_tx for w in basket])

# Helper function for WordCloud
def make_wordcloud(counter_obj, title, filename, width=500, height=500, background_color="black"):
    wc = WordCloud(width=width, height=height, background_color=background_color)
    wc.generate_from_frequencies(counter_obj)

    plt.figure(figsize=(10, 12))
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    plt.title(title)

    # Save with matching facecolor
    save_path = os.path.join(PLOTS_DIR, filename)
    plt.tight_layout()
    plt.savefig(save_path, dpi=200, facecolor=background_color)
    plt.show()
    plt.close()
    print(f"Saved WordCloud: {save_path}")
# Generate and save WordClouds
make_wordcloud(counter_comments_tx, "WordCloud — Comments", "wordcloud_comments.png")
make_wordcloud(counter_captions_tx, "WordCloud — Captions", "wordcloud_captions.png")

"""## Cluster graph of word associations"""

import os
from collections import Counter
from itertools import combinations
import matplotlib.pyplot as plt
import networkx as nx
from nltk.corpus import stopwords
from networkx.algorithms.community import greedy_modularity_communities


PLOTS_DIR = "./plots"
os.makedirs(PLOTS_DIR, exist_ok=True)
stop_words = set(stopwords.words('english'))
def get_pairs_nostop(transactions):
    pairs_counter = Counter()
    for basket in transactions:
        words = [w for w in basket if w not in stop_words]
        for a, b in combinations(sorted(set(words)), 2):
            pairs_counter[(a, b)] += 1
    return pairs_counter
pairs_comments_nostop = get_pairs_nostop(comments_tx)
pairs_captions_nostop = get_pairs_nostop(captions_tx)
def plot_cluster_graph(pair_counter, top_edges, title, filename):
    top = pair_counter.most_common(top_edges)
    if not top:
        print("No edges to plot:", title)
        return
    G = nx.Graph()
    for (a, b), w in top:
        G.add_edge(a, b, weight=w)

    communities = list(greedy_modularity_communities(G))
    pos = nx.spring_layout(G, seed=42)
    plt.figure(figsize=(10, 10))
    nx.draw_networkx_edges(G, pos, alpha=0.25, edge_color='black')
    for i, comm in enumerate(communities):
        nx.draw_networkx_nodes(
            G, pos,
            nodelist=list(comm),
            node_size=200,
            alpha=0.85,
            label=f"Cluster {i+1}"
        )


    nx.draw_networkx_labels(G, pos, font_size=8, font_color='black')
    plt.title(title)
    plt.axis("off")
    plt.legend(loc="best")
    plt.tight_layout()
    filepath = os.path.join(PLOTS_DIR, filename)
    plt.savefig(filepath, dpi=200)
    plt.show()
    plt.close()
    print("Saved cluster graph:", filepath)
plot_cluster_graph(pairs_comments_nostop, 150, "Cluster graph — Comments", "cluster_comments.png")
plot_cluster_graph(pairs_captions_nostop, 150, "Cluster graph — Captions", "cluster_captions.png")

"""## Compare patterns from captions vs comments."""

def top_rules_table(rules_df, topn=15):
    if rules_df.empty:
        return pd.DataFrame(columns=["A","C","support","confidence","lift"])
    t = rules_df.head(topn).copy()
    return t[["antecedents_str","consequents_str","support","confidence","lift"]].rename(
        columns={"antecedents_str":"A","consequents_str":"C"}
    )

top_comments_tbl = top_rules_table(rules_comments, 15)
top_captions_tbl = top_rules_table(rules_captions, 15)
top_comments_tbl.to_csv(os.path.join(CSVS_DIR, "top15_rules_comments.csv"), index=False)
top_captions_tbl.to_csv(os.path.join(CSVS_DIR, "top15_rules_captions.csv"), index=False)
print("Saved top rules tables for comparison.")
print("\nTop comments rules (sample):")
print(top_comments_tbl.head(5).to_string(index=False))
print("\nTop captions rules (sample):")
print(top_captions_tbl.head(5).to_string(index=False))

"""## 3 insight statements and label with metrics"""

def make_insights(rules_df, k=3):
    if rules_df.empty:
        return ["No strong rules found at current thresholds."]
    top = rules_df.sort_values(["lift","confidence"], ascending=False).head(k)
    lines = []
    for _, r in top.iterrows():
        lines.append(
            f"If a text contains [{r['antecedents_str']}], it often also contains [{r['consequents_str']}]. "
            f"(support={r['support']:.3f}, confidence={r['confidence']:.3f}, lift={r['lift']:.3f})"
        )
    return lines

insights_comments = make_insights(rules_comments, 3)
insights_captions = make_insights(rules_captions, 3)
with open(os.path.join(TEXT_DIR, "insights_comments.txt"), "w", encoding="utf-8") as f:
    f.write("\n".join(insights_comments))
with open(os.path.join(TEXT_DIR, "insights_captions.txt"), "w", encoding="utf-8") as f:
    f.write("\n".join(insights_captions))
print("Insights for comments:")
for s in insights_comments:
    print("-", s)
print("\nInsights for captions:")
for s in insights_captions:
    print("-", s)

"""## Save final cleaned dataset with itemsets and rules"""

import pandas as pd
import os

CSVS_DIR = "./csvs"
os.makedirs(CSVS_DIR, exist_ok=True)


comments_tx_df = pd.DataFrame({
    "id": range(1, len(comments_tx)+1),
    "tokens": comments_tx
})
captions_tx_df = pd.DataFrame({
    "id": range(1, len(captions_tx)+1),
    "tokens": captions_tx
})

comments_tx_df.to_csv(os.path.join(CSVS_DIR, "transactions_comments.csv"), index=False)
captions_tx_df.to_csv(os.path.join(CSVS_DIR, "transactions_captions.csv"), index=False)
ap_comments_01_23.to_csv(os.path.join(CSVS_DIR, "final_frequent_itemsets_comments_len2_3.csv"), index=False)
rules_comments.to_csv(os.path.join(CSVS_DIR, "final_association_rules_comments.csv"), index=False)
ap_captions_01_23.to_csv(os.path.join(CSVS_DIR, "final_frequent_itemsets_captions_len2_3.csv"), index=False)
rules_captions.to_csv(os.path.join(CSVS_DIR, "final_association_rules_captions.csv"), index=False)
ap_merged_01_23.to_csv(os.path.join(CSVS_DIR, "final_frequent_itemsets_merged_len2_3.csv"), index=False)
rules_merged.to_csv(os.path.join(CSVS_DIR, "final_association_rules_merged.csv"), index=False)
print("saved transactions & itemsets & rules.")

"""## Save all plots as PNG images"""

print("Saved plot files:")
for fn in sorted(os.listdir(PLOTS_DIR)):
    print(" -", fn)

"""## Reflection Q1 to Q3"""

surprising_pair = pairs_comments_nostop.most_common(1)[0] if len(pairs_comments_nostop) else (("N/A","N/A"), 0)
q1 = f"Surprising pair observed: '{surprising_pair[0][0]}' & '{surprising_pair[0][1]}' (count={surprising_pair[1]}). Why surprising? <write your reason>"
q2 = "What was challenging about finding patterns? <write your answer>"
q3 = "What would you explore next? <write your answer>"

reflection_text = "\n\n".join([
    "Reflection ",
    "Q1: " + q1,
    "Q2: " + q2,
    "Q3: " + q3
])
ref_path = os.path.join(TEXT_DIR, "reflection_answers.txt")
with open(ref_path, "w", encoding="utf-8") as f:
    f.write(reflection_text)
print(f"Reflection template successfully created and saved at:\n{ref_path}\n")
print("TEMPLATE PREVIEW START \n")
print(reflection_text)
print("\nTEMPLATE PREVIEW END")

"""## Answers with a sample response."""

sample_path = os.path.join(TEXT_DIR, "sample_reflection_answers.txt")  # <-- place your sample file here
with open(os.path.join(TEXT_DIR, "reflection_answers.txt"), "r", encoding="utf-8") as f:
    user_text = f.read()
if os.path.exists(sample_path):
    with open(sample_path, "r", encoding="utf-8") as f:
        sample_text = f.read()
else:
    sample_text = "Sample reflection answers not found."

print("My REFLECTION \n")
print(user_text)
print("\n SAMPLE REFLECTION \n")
print(sample_text)
print("\n END OF COMPARISON \n")

"""## Submit all files in a folder named Lab3_PatternMining_Farhatun_Nahar_Priya"""

import os

os.makedirs("/kaggle/working/Lab3_PatternMining_Farhatun_Nahar_Priya", exist_ok=True)

import os
import shutil

OUTDIR = "/kaggle/working/"
SUBMISSION_FOLDER = os.path.join(OUTDIR, "Lab3_PatternMining_Farhatun_Nahar_Priya")


os.makedirs(SUBMISSION_FOLDER, exist_ok=True)
CSVS_SUBFOLDER = os.path.join(SUBMISSION_FOLDER, "CSV Files")
os.makedirs(CSVS_SUBFOLDER, exist_ok=True)


original_csv_files = [
    "/kaggle/working/csvs/transactions_comments.csv",
    "/kaggle/working/csvs/transactions_captions.csv",
    "/kaggle/working/csvs/final_association_rules_comments.csv",
    "/kaggle/working/csvs/final_association_rules_captions.csv",
    "/kaggle/working/csvs/final_association_rules_merged.csv"
]

for f in original_csv_files:
    if os.path.exists(f):
        shutil.copy(f, CSVS_SUBFOLDER)

reuse_files = [
    os.path.join(CSVS_SUBFOLDER, "transactions_comments.csv"),
    os.path.join(CSVS_SUBFOLDER, "transactions_captions.csv"),
    os.path.join(CSVS_SUBFOLDER, "final_association_rules_comments.csv"),
    os.path.join(CSVS_SUBFOLDER, "final_association_rules_captions.csv"),
    os.path.join(CSVS_SUBFOLDER, "final_association_rules_merged.csv"),
]

print("Reuse checklist- Lab3_PatternMining_Farhatun_Nahar_Priya:")
for p in reuse_files:
    status = "OK" if os.path.exists(p) else "MISSING"
    rel_path = p.replace(OUTDIR, "Lab3_PatternMining_Farhatun_Nahar_Priya/")
    print(f"{status} - {rel_path}")